package com.forerunnergames.peril.core.model.game;

public enum CacheKey
{
  BATTLE_ATTACK_VECTOR,
  BATTLE_ATTACK_ORDER,
  FINAL_BATTLE_ACTOR_ATTACKER,
  FINAL_BATTLE_ACTOR_DEFENDER,
  OCCUPY_SOURCE_COUNTRY,
  OCCUPY_TARGET_COUNTRY,
  OCCUPY_PREV_OWNER,
  OCCUPY_NEW_OWNER,
  OCCUPY_MIN_ARMY_COUNT,
  OCCUPY_MAX_ARMY_COUNT,
  PLAYER_OCCUPIED_COUNTRY,
  FORTIFY_VALID_VECTORS,
  FORTIFY_SOURCE_COUNTRY_ID,
  FORTIFY_TARGET_COUNTRY_ID,
  END_PLAYER_TURN_VERIFIED
}
