package com.forerunnergames.peril.client.ui.screens;

public enum ScreenId
{
  LOADING,
  MAIN_MENU,
  MULTIPLAYER_GAME_MODES_MENU,
  MULTIPLAYER_CLASSIC_GAME_MODE_MENU,
  MULTIPLAYER_PERIL_GAME_MODE_MENU,
  MULTIPLAYER_CLASSIC_GAME_MODE_CREATE_GAME_MENU,
  MULTIPLAYER_CLASSIC_GAME_MODE_JOIN_GAME_MENU,
  PLAY_CLASSIC,
  PLAY_PERIL
}
